apiVersion: v1
kind: Pod
metadata:
  name: clarak8
spec:
  containers:
  - name: clarak8
    image: nvcr.io/nvidian/dlmed/clara-train-sdk:v3.1.01
    imagePullPolicy: Never
    command: ['sh', '-c', '/claraDevDay/GettingStarted/commands/train_W_Config.sh trn_base.json']
    resources:
      limits:
        nvidia.com/gpu: 1
    volumeMounts:
    - name: clarak8-storage
      mountPath: /claraDevDay
  restartPolicy: Never
  volumes:
  - name: clarak8-storage
    hostPath:
      # directory location on host
      path: /raid/users/aharouni/dockers/claraTrain2.0/DevDay/
